#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export MMC_SERVER_APP_STORAGE_DIRECTORY="${XDG_STATE_HOME:-$HOME/.local/state}/mmc"

cd "$SCRIPT_DIR/app"
exec "$SCRIPT_DIR/runtime/node" main.js
